-- NIKAHFIX - Supabase Setup
-- Jalankan script ini di Supabase SQL Editor:
-- Dashboard Supabase → SQL Editor → New Query → Paste → Run

-- Buat tabel wishes
CREATE TABLE IF NOT EXISTS wishes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  message TEXT NOT NULL,
  color TEXT,
  attendance TEXT DEFAULT 'belum-konfirmasi',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Aktifkan Row Level Security
ALTER TABLE wishes ENABLE ROW LEVEL SECURITY;

-- Izinkan siapa saja membaca ucapan (tanpa login)
CREATE POLICY "Siapa saja bisa baca ucapan"
  ON wishes FOR SELECT
  USING (true);

-- Izinkan siapa saja mengirim ucapan (tanpa login)
CREATE POLICY "Siapa saja bisa kirim ucapan"
  ON wishes FOR INSERT
  WITH CHECK (true);
